### ISSUE TITLE
Code completion does not work with coc.nvim

### ISSUE THREAD

**Issue by yuntan** [julia-vscode/LanguageServer.jl#390]
Code completion does not work with coc.nvim. Diagnostics and Hover are working.

## Environment
- Julia v1.1.0
- coc.nvim commit 64b3ee0

```
julia> Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 4 entries:
  "IJulia"         => v"1.20.0"
  "StaticLint"     => v"0.2.2"
  "LanguageServer" => v"0.6.1"
  "SymbolServer"   => v"0.2.4"
```

coc-settings.json:

```json
{
  "languageserver": {
    "julia": {
      "command": "julia",
      "args": ["--startup-file=no", "--history-file=no", "/home/me/.config/nvim/langserver.jl"],
      "filetypes": ["julia"]
    },
  }
}
```

langserver.jl:

```julia
import Pkg, LanguageServer, StaticLint, SymbolServer, Sockets

env_path = dirname(Pkg.Types.Context().env.project_file)
depot_path = joinpath(ENV["HOME"], ".julia")
debug = false
# server = LanguageServer.LanguageServerInstance(stdin, stdout, debug, env_path, depot_path, Dict())
server = LanguageServer.LanguageServerInstance(stdin, stdout, debug, env_path, "", Dict())
server.runlinter = true
run(server)
```

## Logs
stdout/stderr required by `:CocInfo`:

```
## Output channel: languageserver.julia

[ Info: Started symbol server
[ Info: store set
ERROR: 
LoadError: 
MethodError: no method matching Tokenize.Tokens.RawToken(::Tokenize.Tokens.Kind, ::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}, ::Int64, ::Int64, ::Tokenize.Tokens.TokenError, ::Bool)
Closest candidates are:
  Tokenize.Tokens.RawToken(::Tokenize.Tokens.Kind, ::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}, ::Int64, ::Int64, ::Tokenize.Tokens.TokenError, ::Bool, !Matched::Bool) at /home/azusa/.julia/packages/Tokenize/xA1lh/src/token.jl:70
  Tokenize.Tokens.RawToken(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, !Matched::Any) at /home/azusa/.julia/packages/Tokenize/xA1lh/src/token.jl:70
  Tokenize.Tokens.RawToken(::Tokenize.Tokens.Kind, ::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}, ::Int64, ::Int64) at /home/azusa/.julia/packages/Tokenize/xA1lh/src/token.jl:82

Stacktrace:

 [1] 
get_toks
(
::
LanguageServer.Document, 
::Int64) at /home/azusa/.julia/packages/LanguageServer/j2G4Z/src/utilities.jl:139
 [2] get_partial_completion(::LanguageServer.Document, ::Int64) at /home/azusa/.julia/packages/LanguageServer/j2G4Z/src/requests/completions.jl:123
 [3] process(::
LanguageServer.JSONRPC.Request{Val{
Symbol("textDocument/completion")},LanguageServer.CompletionParams}, ::LanguageServer.LanguageServerInstance) at /home/azusa/.julia/packages/LanguageServer/j2G4Z/src/requests/completions.jl:24

 [4] run(::LanguageServer.LanguageServerInstance) at /home/azusa/.julia/packages/LanguageServer/j2G4Z/src/languageserverinstance.jl:47
 [5] top-level scope at none:0
 [6] 
include at ./boot.jl:326 [inlined]

 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] exec_options(::
Base.JLOptions) at ./client.jl:267
 [10] _start()
 at ./client.jl:436
in expression starting at /home/azusa/.config/nvim/langserver.jl:9
[Info  - 2:29:33 PM] Connection to server got closed. Server will restart.
[Error  - 2:29:33 PM] Request textDocument/completion failed.
Error: Connection got disposed.
    at Object.dispose (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:38591:25)
    at Object.dispose (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:76650:35)
    at LanguageClient.handleConnectionClosed (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:78771:42)
    at LanguageClient.handleConnectionClosed (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:76277:15)
    at closeHandler (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:78757:18)
    at CallbackList.invoke (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:39233:39)
    at Emitter.fire (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:39291:36)
    at closeHandler (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:37941:26)
    at CallbackList.invoke (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:39233:39)
    at Emitter.fire (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:39291:36)
[Error  - 2:29:33 PM] Request textDocument/completion failed.
Error: Connection got disposed.
    at Object.dispose (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:38591:25)
    at Object.dispose (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:76650:35)
    at LanguageClient.handleConnectionClosed (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:78771:42)
    at LanguageClient.handleConnectionClosed (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:76277:15)
    at closeHandler (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:78757:18)
    at CallbackList.invoke (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:39233:39)
    at Emitter.fire (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:39291:36)
    at closeHandler (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:37941:26)
    at CallbackList.invoke (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:39233:39)
    at Emitter.fire (/home/azusa/.local/share/nvim/plugged/coc.nvim/build/index.js:39291:36)
[Error  - 2:29:33 PM] julia exited with code: 1
[ Info: Started symbol server
[ Info: store set
```

**Comment by 313v** [comment]
Hi @davidanthoff  - i did some work to scope this bug.

Basically the problem is that RawToken now takes one extra boolean as a parameter (suffix - whatever that means)

by checking out a dev version of languageserver and passing false I was able to get things working after also getting a dev version of SymbolServer (because of .PackageRef reference not being found)

this got things mostly working but for some reason i get "Missing Reference: XXXX" for every single using - like this:

using JSON   "Missing Reference: JSON"
using REPL   "Missing Reference: REPL"
etc...

type completion does seem to work though

any guidance on how to help you resolve this, let me know

**Comment by ZacLN** [comment]
Updating to the latest version of LanguageServer should have resolved this, let me know if not

**Comment by a-torgovitsky** [comment]
I am using @yuntan 's same `coc-settings.json` and `langserver.jl` file, and I am having problems with this. Here is what I get in `:CocInfo`:
```
## Output channel: languageserver.julia

ERROR: 
LoadError: 
MethodError: Cannot `convert` an object of type String to an object of type Function
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:154

Stacktrace:

 [1] 
convert
(
::
Type{
Union
{
Nothing, Function}
}, ::String) at ./some.jl:22
 [2] JSONRPC.JSONRPCEndpoint(::Base.PipeEndpoint, ::Base.PipeEndpoint, ::String) at /home/at/.julia/packages/JSONRPC/1Kq3H/src/core.jl:61
 [3] LanguageServer.LanguageServerInstance(::
Base.PipeEndpoint, ::Base.PipeEndpoint, ::Bool, ::String, ::String, 
::Dict{Any,Any}) at /home/at/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:66
 [4] top-level scope
 at none:0
 [5] 
include at 
./boot.jl:326 [inlined]
 [6] include_relative(::Module, ::String) at ./loading.jl:1038
 [7] include(::Module, ::String) at ./sysimg.jl:29
 [8] exec_options(::Base.JLOptions) at 
./client.jl:267
 [9] _start() at ./client.jl:436
in expression starting at /home/at/.config/nvim/langserver.jl:9
[Info  - 7:12:33 PM] Connection to server got closed. Server will restart.
[Error  - 7:12:33 PM] julia exited with code: 1
ERROR: 
LoadError: 
MethodError: Cannot `convert` an object of type String to an object of type Function
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:154

Stacktrace:

 [1] 
convert
(
::
Type{
Union
{
Nothing, Function}
}, ::String) at ./some.jl:22
 [2] JSONRPC.JSONRPCEndpoint(::Base.PipeEndpoint, ::Base.PipeEndpoint, ::String) at /home/at/.julia/packages/JSONRPC/1Kq3H/src/core.jl:61
 [3] LanguageServer.LanguageServerInstance(::Base.PipeEndpoint, ::Base.PipeEndpoint
, ::Bool, ::String, ::String, ::Dict{Any,Any}) at 
/home/at/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:66
 [4] top-level scope at none:0
 [5] 
include at ./boot.jl:326
 [inlined]
 [6] include_relative(::Module, ::String) at ./loading.jl:1038
 [7] include(::Module, ::String) at ./sysimg.jl:29
 [8] exec_options(::Base.JLOptions
) at ./client.jl:267
 [9] _start() at ./client.jl:436
in expression starting at /home/at/.config/nvim/langserver.jl:9
[Info  - 7:12:37 PM] Connection to server got closed. Server will restart.
[Error  - 7:12:37 PM] julia exited with code: 1
ERROR: 
LoadError: 
MethodError: Cannot `convert` an object of type String to an object of type Function
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:154

Stacktrace:

 [1] 
convert
(
::
Type{
Union
{
Nothing, Function}}
, ::String) at ./some.jl:22
 [2] JSONRPC.JSONRPCEndpoint(::Base.PipeEndpoint, ::Base.PipeEndpoint, ::String) at /home/at/.julia/packages/JSONRPC/1Kq3H/src/core.jl:61
 [3] LanguageServer.LanguageServerInstance(::Base.PipeEndpoint, ::Base.PipeEndpoint, ::Bool, ::String, ::String, ::Dict{Any,Any}) at /home/at/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:66
 [4] top-level scope at none:0
 [5] 
include at ./boot.jl:326 [inlined]
 [6] 
include_relative(::Module, ::String) at ./loading.jl:1038
 [7] include(::Module, ::String) at ./sysimg.jl:29
 [8] exec_options(::Base.JLOptions) at ./client.jl:267
 [9] _start() at ./client.jl:436
in expression starting at /home/at/.config/nvim/langserver.jl:9
[Info  - 7:12:40 PM] Connection to server got closed. Server will restart.
[Error  - 7:12:40 PM] julia exited with code: 1
ERROR: 
LoadError: 
MethodError: Cannot `convert` an object of type String to an object of type Function
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:154

Stacktrace:

 [1] 
convert
(
::
Type{
Union
{
Nothing, Function}
}, ::String) at ./some.jl:22
 [2] JSONRPC.JSONRPCEndpoint(::Base.PipeEndpoint, ::Base.PipeEndpoint, ::String) at /home/at/.julia/packages/JSONRPC/1Kq3H/src/core.jl:61
 [3] LanguageServer.LanguageServerInstance(::Base.PipeEndpoint, ::Base.PipeEndpoint, ::Bool, ::String, ::String, ::Dict{Any,Any}) at /home/at/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:66
 [4] top-level scope at none:0
 [5] 
include at ./boot.jl:326 [inlined]
 [6] 
include_relative(::Module, ::String) at ./loading.jl:1038
 [7] include(::Module, ::String) at ./sysimg.jl:29
 [8] exec_options(::Base.JLOptions) at ./client.jl:267
 [9] _start() at ./client.jl:436
in expression starting at /home/at/.config/nvim/langserver.jl:9
[Info  - 7:12:44 PM] Connection to server got closed. Server will restart.
[Error  - 7:12:44 PM] julia exited with code: 1


```

Any ideas?
